#include "pch.h"
#include "polynom.h"
#include <iostream>
using namespace std;
int main()
{
	setlocale(LC_ALL, "Russian");
	string a, b;
	cout << "Введите первый полином с переменными x,y или z: ";
	getline(cin, a);
	polynom p(a);
//	p.Calculate(3);
	cout << endl;
	cout << "Введённый полином: " << p.GetString() << endl;
	cout << endl;
	cout << "Введите второй полином с переменными x,y или z: ";
	getline(cin, b);
	polynom p1(b);
	cout << endl;
	cout << "Введённый полином: " << p1.GetString() << endl;
	cout << endl;
	polynom nom = p + p1;
	cout << "Сумма полиномов: " << nom.GetString() << endl;
	cout << endl;
	nom = p - p1;
	cout << "Разность первого и второго: " << nom.GetString() << endl;
	cout << endl;
	nom = p * p1;
	cout << "Произведение: " << nom.GetString() << endl;
	cout << endl;
	int scal;
	cout << "Введите скаляр: ";
	cin >> scal;
	cout << endl;
	nom = p * scal;
	cout << "Произведение 1-го полинома на этот скаляр" << nom.GetString() << endl;
	cout << endl;
	char l;
	cout << "Введите переменную для дифференцирования (х, у или z): ";
	cin >> l;
	cout << endl;
	nom = p.derative(l);
	cout << "Производная 1-го полинома по переменной " << l << " :" << nom.GetString() << endl;
	nom = p1.derative(l);
	cout << endl;
	cout << "Производная 2-го полинома по переменной " << l << " :" << nom.GetString() << endl;
	cout << endl;
	cout << "Введите переменную для вычисление первообразной (х, у или z): ";
	cin >> l;
	cout << endl;
	nom = p.integration(l);
	cout << "Интеграл 1-го полинома по переменной " << l << " :" << nom.GetString() << endl;
	nom = p1.integration(l);
	cout << endl;
	cout << "Интеграл 2-го полинома по переменной " << l << " :" << nom.GetString() << endl;
	cout << endl;
	double tmp[3];
	cout << "Введите точку, в которой будет вычислен полином: " << endl;
	cout << endl;
	cout << "x: ";
	cin >> tmp[0];
	cout << "y: ";
	cin >> tmp[1];
	cout << "z: ";
	cin >> tmp[2];
	double cal = p.Calculate(tmp);
	cout << "Значение 1-го полинома в точке: " << cal << endl;
	cout << endl;
    cal = p1.Calculate(tmp);
	cout << "Значение 2-го полинома в точке: " << cal << endl;
}
